import assert from "node:assert/strict";
import { createServer } from "vite";
import { fileURLToPath } from "node:url";

const server = await createServer({ root: fileURLToPath(new URL("..", import.meta.url)), appType: "custom", logLevel: "silent", server: { middlewareMode: true, watch: null } });
try {
  const { WebMcpAdapter, nativeModelContext } = await server.ssrLoadModule("/src/lib/webmcp/adapter.ts");
  const { objectSchema } = await server.ssrLoadModule("/src/lib/webmcp/types.ts");
  const { JobRegistry } = await server.ssrLoadModule("/src/lib/webmcp/jobs.ts");
  const jobs = new JobRegistry();
  const registered = new Map();
  let revision = "1", available = true, writes = 0;
  const provider = { registerTool(tool, { signal }) {
    if (tool.name === "broken") throw Error("isolated registration failure");
    registered.set(tool.name, { tool, signal });
    signal.addEventListener("abort", () => registered.delete(tool.name), { once: true });
  } };
  const context = signal => ({ signal, jobs, runtime: null, hosted: null, shell: null, capabilities: null });
  const adapter = new WebMcpAdapter({ provider, context, revision: () => revision });
  const base = { title: "Test action", description: "Deterministic test action", scope: "public", group: "test", inputSchema: objectSchema({ value: { type: "integer", minimum: 0, maximum: 10 } }, ["value"]), annotations: { readOnlyHint: false }, execute: input => { writes++; return input.value; } };
  const mutation = { ...base, name: "change", available: () => available ? null : "No model" };
  await adapter.setTools([mutation, { ...base, name: "broken" }, adapter.resultTool()]);
  assert.equal(adapter.errors.get("broken"), "isolated registration failure");
  assert.ok(registered.has("change"));
  for (const input of [{ value: "1" }, { value: 11 }, { value: 2, surprise: true }, JSON.parse('{"value":1,"__proto__":{}}')]) {
    assert.equal((await adapter.execute("change", input)).error.code, "invalid_input");
  }
  assert.equal(writes, 0);
  const first = await adapter.execute("change", { value: 2, request_id: "same", expected_revision: "1" });
  revision = "2";
  assert.deepEqual(await adapter.execute("change", { value: 2, request_id: "same", expected_revision: "1" }), first);
  assert.deepEqual(await adapter.execute("change", { request_id: "same", expected_revision: "1", value: 2 }), first);
  assert.equal(writes, 1);
  assert.equal((await adapter.execute("change", { value: 3, request_id: "same" })).error.code, "request_conflict");
  assert.equal((await adapter.execute("change", { value: 2, expected_revision: "1" })).error.code, "stale_state");
  const abort = new AbortController(); abort.abort();
  assert.equal((await adapter.execute("change", { value: 3 }, abort.signal)).error.code, "cancelled");
  assert.equal(writes, 1);
  available = false; await adapter.refresh();
  assert.equal(registered.has("change"), false);
  assert.equal((await adapter.execute("change", { value: 2 })).error.code, "unavailable");
  available = true; await adapter.refresh();
  assert.ok(registered.has("change"));
  const oldCallback = registered.get("change").tool.execute;
  await adapter.setTools([{ ...mutation, execute: () => { throw Error("Stale call reached replacement action"); } }]);
  assert.equal((await oldCallback({ value: 1 }, { signal: new AbortController().signal })).error.code, "unavailable");
  const union = { ...base, name: "union", inputSchema: { anyOf: [objectSchema({ op: { type: "string", enum: ["fit"] } }, ["op"]), objectSchema({ op: { type: "string", enum: ["fetch"] }, source: { type: "string" } }, ["op", "source"])] }, execute: value => value };
  const long = { ...base, name: "long", inputSchema: objectSchema(), annotations: { readOnlyHint: true, untrustedContentHint: true }, execute: () => ({ prose: "untrusted ".repeat(2000) }) };
  await adapter.setTools([union, long, adapter.resultTool()]);
  assert.equal((await adapter.execute("union", { op: "fit", request_id: "union" })).ok, true);
  assert.equal((await adapter.execute("union", { op: "fit", source: "ignored" })).ok, false);
  const large = await adapter.execute("long", {});
  assert.ok(large.result_id);
  let json = "", offset = 0;
  do {
    const page = await adapter.execute("drowse_read_result", { result_id: large.result_id, offset });
    json += page.data.text; offset = page.data.next_offset;
  } while (offset !== null);
  assert.equal(JSON.parse(json).data.prose.length, 20000);
  adapter.dispose(); assert.equal(registered.size, 0);
  assert.equal((await adapter.execute("union", { op: "fit" })).error.code, "unavailable");
  assert.equal(nativeModelContext(), null);
  const unsupported = new WebMcpAdapter({ provider: null, context });
  await unsupported.setTools([base]); unsupported.dispose();
  let releaseLoad;
  const load = jobs.start("model_load", () => new Promise(resolve => { releaseLoad = resolve; }), { cancellable: false });
  const analysis = jobs.start("token-readout", () => new Promise(() => {}));
  await Promise.resolve();
  jobs.interrupt("Model identity changed", job => job.kind !== "model_load");
  assert.equal(jobs.get(analysis.id).state, "interrupted");
  assert.equal(jobs.get(load.id).state, "running", "A deliberate model switch must not interrupt its own load receipt");
  releaseLoad({ model_id: "model-b" });
  await new Promise(resolve => setTimeout(resolve, 0));
  assert.equal(jobs.get(load.id).state, "completed");
  const storageData = new Map();
  const storage = { getItem: key => storageData.get(key) ?? null, setItem: (key, value) => storageData.set(key, value) };
  const durable = new WebMcpAdapter({ provider: null, context, requestStorage: storage });
  await durable.setTools([mutation]);
  const completedReceipt = await durable.execute("change", { value: 4, request_id: "across-reload" });
  const beforeReloadWrites = writes;
  durable.dispose();
  const reloaded = new WebMcpAdapter({ provider: null, context, requestStorage: storage });
  await reloaded.setTools([mutation]);
  assert.deepEqual(await reloaded.execute("change", { value: 4, request_id: "across-reload" }), completedReceipt);
  assert.equal(writes, beforeReloadWrites, "Reload reconciliation must not execute a completed mutation again");
  assert.equal((await reloaded.execute("change", { value: 5, request_id: "across-reload" })).error.code, "request_conflict");
  let finishPending;
  await reloaded.setTools([{ ...mutation, execute: () => new Promise(resolve => { finishPending = resolve; }) }]);
  const pendingCall = reloaded.execute("change", { value: 6, request_id: "uncertain" });
  await new Promise(resolve => setTimeout(resolve, 0));
  const interruptedPage = new WebMcpAdapter({ provider: null, context, requestStorage: storage });
  await interruptedPage.setTools([mutation]);
  assert.equal((await interruptedPage.execute("change", { value: 6, request_id: "uncertain" })).error.code, "reconcile_required");
  assert.equal(writes, beforeReloadWrites);
  finishPending(6); await pendingCall;
  const { ApiError } = await server.ssrLoadModule("/src/lib/runtime/errors.ts");
  await interruptedPage.setTools([{ ...mutation, execute: () => { throw new ApiError(409, "/model", "Missing fit", { code: "FIT_REQUIRED", detail: { missing: ["whitener"], api_key: "never-return-this" } }); } }]);
  const prerequisite = await interruptedPage.execute("change", { value: 1 });
  assert.equal(prerequisite.error.code, "FIT_REQUIRED");
  assert.equal(prerequisite.error.details.status, 409);
  assert.deepEqual(prerequisite.error.details.response.detail.missing, ["whitener"]);
  assert.equal(prerequisite.error.details.response.detail.api_key, "[redacted]");
  const liveState = new Proxy({ filter: new Proxy({ expression: "pirate" }, {}) }, {});
  await interruptedPage.setTools([{ ...mutation, execute: () => liveState }]);
  const plainResult = await interruptedPage.execute("change", { value: 1 });
  assert.deepEqual(structuredClone(plainResult).data, { filter: { expression: "pirate" } }, "Native consumers must receive plain JSON, including reactive UI state");
  liveState.filter.expression = "new human edit";
  assert.equal(plainResult.data.filter.expression, "pirate", "Returned settings are a stable result snapshot");
  reloaded.dispose(); interruptedPage.dispose();
  console.log("WebMCP adapter: schema validation, capabilities, stale state, idempotency, cancellation, pagination and native lifetime isolation passed");
} finally { await server.close(); }
