import assert from "node:assert/strict";
import { fileURLToPath } from "node:url";
import { createServer } from "vite";
import puppeteer from "puppeteer";

const root = fileURLToPath(new URL("..", import.meta.url)).replace(/\/$/, "");
const server = await createServer({ configFile: `${root}/vite.hosted.config.ts`, logLevel: "error", server: { watch: null, host: "127.0.0.1", port: 0 } });
await server.listen();
const browser = await puppeteer.launch({ headless: true, args: ["--disable-features=WebMCP"] });
const page = await browser.newPage();
await page.setViewport({ width: 1440, height: 1000 });
const errors = [];
page.on("pageerror", error => errors.push(error.message));
const origin = `http://127.0.0.1:${server.httpServer.address().port}`;
async function invoke(name, input = {}) {
  return page.evaluate(async ({ root, name, input }) => {
    const base = `/@fs${root}/src/lib/`;
    const { createWorkspaceTools, assertWorkspaceIdle } = await import(`${base}webmcp/workspaceTools.ts`);
    const { validateInput } = await import(`${base}webmcp/validation.ts`);
    const { getRuntimeClient } = await import(`${base}runtime/registry.ts`);
    const tool = createWorkspaceTools().find(row => row.name === name);
    validateInput(tool.inputSchema, input);
    const value = await tool.execute(input, { runtime: getRuntimeClient(), jobs: { list: () => [] }, signal: new AbortController().signal, assertWorkspaceIdle });
    return JSON.parse(JSON.stringify(value));
  }, { root, name, input });
}
async function mounted(form) {
  await page.waitForFunction(async ({ root, form }) => !!(await import(`/@fs${root}/src/lib/workspaceController.ts`)).getInterfaceController(form), {}, { root, form });
}
try {
  await page.goto(`${origin}/app?layoutFixture=instruments`);
  await page.waitForSelector(".shell");
  await page.evaluate(async root => {
    const registry = await import(`/@fs${root}/src/lib/runtime/registry.ts`);
    const capabilities = registry.getRuntimeCapabilities();
    for (const operation of ["fitting", "manifold_artifacts"]) capabilities.operations[operation] = { available: true, reasons: [] };
    const runtime = registry.getRuntimeClient();
    const template = { namespace: "local", name: "directions", slot: "[SIDE]", values: ["left", "right"], contexts: [{ turns: [{ role: "user", content: "Which way?" }], assistant: "[SIDE]" }], n_values: 2, n_contexts: 1 };
    runtime.templates.list = async () => ({ templates: [template] });
    runtime.templates.get = async () => template;
    runtime.profiles.list = async () => ({ profiles: [{ name: "fixture/a" }, { name: "fixture/b" }] });
    runtime.manifolds.list = async () => ({ manifolds: ["a", "b"].map(name => ({ namespace: "fixture", name, fit_mode: "pca", fitted_for_session: true, node_count: 2, intrinsic_dim: 1, node_labels: ["left", "right"] })) });
  }, root);
  await invoke("drowse_navigate", { drawer: "manifold_builder", params: { mode: "discover" } });
  await mounted("manifold_discover");
  await invoke("drowse_edit_form", { form: "manifold_builder", fields: { name: "pirate trial", description: "A human-reviewed draft" } });
  await invoke("drowse_edit_form", { form: "manifold_discover", fields: { concepts_text: "pirate, assistant", samples_per_prompt: 2, role_per_node: true, custom_system: "You are {c}.", tuning: { maxDim: 2 } } });
  let forms = (await invoke("drowse_read_form")).forms;
  assert.equal(forms.manifold_builder.values.name, "pirate trial");
  assert.equal(forms.manifold_discover.values.role_per_node, true);
  assert.equal(forms.manifold_discover.total_examples, 192);
  assert.ok(await page.$eval('[aria-label="Build manifold"]', node => [...node.querySelectorAll("textarea")].some(input => input.value === "pirate, assistant")));
  await assert.rejects(invoke("drowse_edit_form", { form: "manifold_discover", fields: { ignored_typo: true } }), /unknown property/);
  await invoke("drowse_edit_form", { form: "manifold_builder", fields: { mode: "authored" } });
  await mounted("manifold_authored");
  await invoke("drowse_edit_form", { form: "manifold_authored", fields: { auto_domain: true, nodes: [{ label: "pirate", coords: [0, 0], statements: "Ahoy", role: "pirate", expanded: true }] } });
  assert.equal((await invoke("drowse_read_form", { form: "manifold_authored" })).forms.manifold_authored.values.nodes[0].statements, "Ahoy");
  await invoke("drowse_edit_form", { form: "manifold_builder", fields: { mode: "discover" } });
  assert.equal((await invoke("drowse_read_form", { form: "manifold_discover" })).forms.manifold_discover.values.concepts_text, "pirate, assistant", "hidden visited drafts survive tab switches");
  await invoke("drowse_edit_form", { form: "manifold_builder", fields: { mode: "templated" } });
  await mounted("manifold_templated");
  await page.waitForFunction(async root => (await import(`/@fs${root}/src/lib/workspaceController.ts`)).getInterfaceController("manifold_templated")?.read().available_templates.length > 0, {}, root);
  await invoke("drowse_edit_form", { form: "manifold_templated", fields: { selected_key: "local/directions", max_dim: 2, also_fit: false } });
  assert.equal((await invoke("drowse_read_form", { form: "manifold_templated" })).forms.manifold_templated.values.selected_key, "local/directions");
  await invoke("drowse_navigate", { drawer: "manifold_merge" });
  await mounted("manifold_merge");
  await page.waitForFunction(async root => (await import(`/@fs${root}/src/lib/workspaceController.ts`)).getInterfaceController("manifold_merge")?.read().available_sources.length === 2, {}, root);
  const merge = await invoke("drowse_edit_form", { form: "manifold_merge", fields: { sources: ["fixture/a", "fixture/b"], target_name: "merged", fit_mode: "pca" } });
  assert.equal(merge.can_submit, true);
  await invoke("drowse_navigate", { drawer: "compare" });
  await mounted("profile_compare");
  await page.waitForFunction(async root => (await import(`/@fs${root}/src/lib/workspaceController.ts`)).getInterfaceController("profile_compare")?.read().available_profiles.length >= 2, {}, root);
  const compare = await invoke("drowse_set_analysis_view", { target: "profile_compare", fields: { profile_a: "fixture/b", profile_b: "fixture/a" } });
  assert.equal(compare.values.profile_a, "fixture/b");
  await invoke("drowse_navigate", { drawer: "template_lab", params: { tab: "build" } });
  await mounted("template_lab");
  await invoke("drowse_edit_form", { form: "template_lab", fields: { name: "direction", slot: "[SIDE]", values_text: "left, right", contexts: [{ turns: [{ role: "user", content: "Choose a direction" }], assistant: "Turn [SIDE]." }] } });
  forms = (await invoke("drowse_read_form")).forms;
  assert.deepEqual(forms.template_lab.validation, []);
  assert.ok(await page.$eval('[aria-label="Template lab"]', node => [...node.querySelectorAll("input,textarea")].some(input => input.value === "Turn [SIDE].")));
  const revision = (await invoke("drowse_read_workspace")).revision;
  await page.$eval('[aria-label="Template lab"] input', input => { input.value = "human renamed draft"; input.dispatchEvent(new Event("input", { bubbles: true })); });
  assert.notEqual((await invoke("drowse_read_workspace")).revision, revision, "human form typing changes revision");
  await invoke("drowse_navigate", { drawer: null, view: "conversation" });
  await invoke("drowse_set_composer", { text: "Pirate search prompt" });
  const before = (await invoke("drowse_read_workspace")).revision;
  await page.$eval("textarea", input => { input.value += " human edit"; input.dispatchEvent(new Event("input", { bubbles: true })); });
  assert.notEqual((await invoke("drowse_read_workspace")).revision, before, "human composer typing changes revision");
  await page.evaluate(async root => {
    const { applyTreeSnapshot, loomTree } = await import(`/@fs${root}/src/lib/stores.svelte.ts`);
    const make = (id, parent_id, text, role = "assistant") => ({ id, parent_id, text, role, role_label: null, recipe: null, finish_reason: "stop", aggregate_readings: {}, thinking_tokens: [], tokens: (text.match(/\S+\s*/g) ?? []).map((text, raw_index) => ({ text, raw_index, token_id: raw_index + 1, logprob: -0.2 })) });
    applyTreeSnapshot({ tree_format: 2, drowse_version: "test", session_id: loomTree.session_id, model_id: loomTree.modelId, root_id: "root", active_node_id: "a", rev: loomTree.rev + 100, nodes: [make("root", null, "", "system"), make("prompt", "root", "Reply", "user"), make("a", "prompt", "Ahoy pirate friend"), make("b", "prompt", "Hello friend")], children_of: { root: ["prompt"], prompt: ["a", "b"], a: [], b: [] }, cast: {} });
  }, root);
  await invoke("drowse_navigate", { drawer: null, loom_view: "map" });
  await page.waitForSelector(".loom-viewport");
  const filtered = await invoke("drowse_set_loom_view", { filter: { expression: "pirate", mode: "text" }, sort: "confidence", selected_node_ids: ["a", "b"], pin_node_id: "b" });
  assert.deepEqual(filtered.filter.matching_node_ids, ["a"]);
  assert.equal(await page.$eval('input[type="search"]', input => input.value), "pirate");
  await invoke("drowse_set_loom_view", { search_match: "first", zoom: 0.7 });
  await invoke("drowse_set_loom_view", { camera: "fit" });
  await invoke("drowse_set_loom_view", { filter: { expression: "text:friend", mode: "advanced" }, collapsed_ids: ["prompt"] });
  assert.deepEqual((await invoke("drowse_read_workspace")).interfaces.loom.values.collapsed_ids, ["prompt"]);
  await invoke("drowse_set_loom_view", { filter: { expression: "", mode: "text" }, collapsed_ids: [], camera: "current" });
  await invoke("drowse_navigate", { view: "conversation" });
  await invoke("drowse_set_loom_view", { comparison_visible: false });
  assert.equal((await invoke("drowse_read_workspace")).interfaces.loom_filter.pin_node_id, null);
  await invoke("drowse_navigate", { drawer: "node_compare", params: { node_ids: ["a", "b"] } });
  await mounted("node_compare");
  const comparisonDisplay = await invoke("drowse_set_analysis_view", { target: "node_compare", fields: { layout: "unified", sort_by: "name" } });
  assert.equal(comparisonDisplay.values.layout, "unified");
  await invoke("drowse_navigate", { drawer: "token_drilldown", params: { turnIdx: 1, tokenIdx: 0 } });
  await mounted("token_inspector");
  const inspector = await invoke("drowse_set_token_inspector", { move: "next", tab: "logits" });
  assert.equal(inspector.values.cursor.tokenIdx, 1);
  await assert.rejects(invoke("drowse_set_token_inspector", { apply_recipe: { geometry: false } }), /Prepare the geometry instrument/);
  await invoke("drowse_attach_probe", { selector: "fixture/mobile-3d" });
  for (const family of ["geometry", "lens", "sae"]) {
    if (inspector.replay[family]) {
      const counterfactual = await invoke("drowse_set_token_inspector", { apply_recipe: { [family]: false } });
      assert.equal(counterfactual.values.apply_recipe[family], false);
    } else await assert.rejects(invoke("drowse_set_token_inspector", { apply_recipe: { [family]: false } }), /token replay/);
    const recorded = await invoke("drowse_set_token_inspector", { apply_recipe: { [family]: true } });
    assert.equal(recorded.values.apply_recipe[family], true);
  }
  await assert.rejects(invoke("drowse_set_token_inspector", { branch: "shadow" }), /no shadow/);
  await page.evaluate(async root => {
    const { chatLog } = await import(`/@fs${root}/src/lib/stores/chat.svelte.ts`);
    const primary = chatLog.turns[1];
    primary.abPair = { ...primary, nodeId: "b", tokens: primary.tokens.map(token => ({ ...token, text: "shadow" })) };
  }, root);
  const shadow = await invoke("drowse_set_token_inspector", { branch: "shadow", cursor: { turnIdx: 1, seg: "response", tokenIdx: 0 } });
  assert.equal(shadow.values.branch, "shadow");
  await invoke("drowse_set_token_inspector", { branch: "primary" });
  await invoke("drowse_set_token_inspector", { presentation: "dock" });
  await mounted("token_inspector");
  assert.equal((await invoke("drowse_read_workspace")).interfaces.token_inspector.values.presentation, "dock");
  await invoke("drowse_set_token_inspector", { presentation: "drawer" });
  await invoke("drowse_set_analysis_view", { target: "lens", fields: { sort: "depth" } });
  await invoke("drowse_set_analysis_view", { target: "sae", fields: { sort: "name" } });
  assert.equal((await invoke("drowse_read_workspace")).interfaces.lens.values.sort, "depth");
  await invoke("drowse_set_token_inspector", { presentation: "hide" });
  await invoke("drowse_navigate", { drawer: "probe_inspector", params: { name: "fixture/mobile-3d" } });
  await mounted("probe_geometry");
  await page.waitForFunction(async root => (await import(`/@fs${root}/src/lib/workspaceController.ts`)).getInterfaceController("probe_geometry")?.read().available_layers.length > 0, {}, root);
  const geometry = await invoke("drowse_set_analysis_view", { target: "probe_geometry", fields: { layer: 1, zoom: 2.1, rotate: { dx: 20, dy: -15 } } });
  assert.equal(geometry.values.layer, 1);
  assert.equal(geometry.values.zoom, 2.1);
  assert.equal(await page.$eval("canvas[data-orbit-zoom]", node => node.dataset.orbitZoom), "2.10");
  const reset = await invoke("drowse_set_analysis_view", { target: "probe_geometry", fields: { reset: true } });
  assert.equal(reset.values.zoom, 1.6);
  await invoke("drowse_navigate", { drawer: "save_conversation", presentation: "sidebar", expanded: true });
  await mounted("chat_identity");
  await page.waitForFunction(async root => !(await import(`/@fs${root}/src/lib/workspaceController.ts`)).getInterfaceController("chat_identity")?.read().busy, {}, root);
  const saved = await invoke("drowse_save_chat", { name: "Saved fixture" });
  await invoke("drowse_edit_form", { form: "chat_identity", fields: { name: "Human unsaved metadata", accent: "mint" } });
  await assert.rejects(invoke("drowse_update_chat", { id: saved.chat.id, name: "overwrite" }), /open chat identity draft/);
  const metadataBefore = (await invoke("drowse_read_workspace")).revision;
  await page.$eval('.save-conversation input, [aria-label="Save conversation"] input, .drawer-shell input', input => { input.value += " human change"; input.dispatchEvent(new Event("input", { bubbles: true })); });
  assert.notEqual((await invoke("drowse_read_workspace")).revision, metadataBefore);
  await page.evaluate(async root => {
    const { pendingActions } = await import(`/@fs${root}/src/lib/stores/pending.svelte.ts`);
    pendingActions.queue.push({ id: "human-pending", label: "human queued reply", text: "human pending text", createdAt: Date.now(), awaitsGen: false, rebuild: null, apply() {}, onCancel() { window.cancelObserved = true; } });
  }, root);
  await invoke("drowse_cancel_pending_action", { id: "human-pending" });
  assert.equal(await page.evaluate(() => window.cancelObserved), true);
  await assert.rejects(invoke("drowse_cancel_pending_action", { id: "human-pending" }), /already ran/);
  assert.equal((await invoke("drowse_read_workspace")).presentation.expanded, true);
  await page.goto(`${origin}/app?layoutFixture=base`);
  await page.waitForSelector('[aria-label="Editable completion buffer"]');
  await invoke("drowse_set_raw_buffer", { action: "edit", text: "A pirate story", selection: { start: 0, end: 1 } });
  const rawRevision = (await invoke("drowse_read_workspace")).revision;
  await page.$eval('[aria-label="Editable completion buffer"]', input => { input.value += " from a human"; input.dispatchEvent(new Event("input", { bubbles: true })); });
  assert.notEqual((await invoke("drowse_read_workspace")).revision, rawRevision, "human raw-buffer edits change revision");
  assert.deepEqual(errors, []);
  console.log("WebMCP UI: actual draft controls, human revision changes, retained forms, visible Loom search/camera/pin, token cursor/docking, display sorting and human pending cancellation passed");
} finally { await browser.close(); await server.close(); }
